# This is a basic workflow to help you get started with Actions

name: Report Grade Results

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "grade" , "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # runs Tues, Jan 30, 2024 at 8:00 PM ET
  schedule:
   - cron: '05 01 31 1 *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# {owner}/{repo}/.github/workflows/{filename}@{ref}
# does the build run in the other repo?
jobs:
  gatorgrade-to-firestore:
    uses: allegheny-college-cmpsc-100-spring-2024/ggfs/.github/workflows/gg-fs.yml@main
    secrets: inherit
    with:
      assignment: 'variables-dtypes-problem-set'
      category: 'problem-sets'
      scrape: true
      